-- Supabase PostgreSQL Schema for Fish Delivery App
-- Run this in the Supabase Dashboard SQL Editor

-- ── Tables ──────────────────────────────────────────────────────────────────

CREATE TABLE IF NOT EXISTS users (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT NOT NULL,
    email TEXT NOT NULL UNIQUE,
    password_hash TEXT NOT NULL,
    role TEXT NOT NULL CHECK(role IN ('seller', 'customer', 'delivery', 'admin')),
    city TEXT DEFAULT '',
    email_verified BOOLEAN DEFAULT false,
    otp_code TEXT,
    otp_expires TIMESTAMP WITH TIME ZONE,
    reset_token TEXT,
    reset_expires TIMESTAMP WITH TIME ZONE,
    last_login TIMESTAMP WITH TIME ZONE,
    login_ip TEXT,
    login_user_agent TEXT,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc', now())
);

CREATE TABLE IF NOT EXISTS fish (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    seller_id BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    name TEXT NOT NULL,
    price REAL NOT NULL,
    image_path TEXT DEFAULT '',
    description TEXT DEFAULT '',
    available INTEGER DEFAULT 1,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc', now())
);

CREATE TABLE IF NOT EXISTS orders (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    order_number TEXT NOT NULL UNIQUE,
    customer_id BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    fish_id BIGINT NOT NULL REFERENCES fish(id) ON DELETE CASCADE,
    quantity REAL NOT NULL,
    total_price REAL NOT NULL,
    status TEXT DEFAULT 'pending',
    assigned_to BIGINT REFERENCES users(id) ON DELETE SET NULL,
    delivery_address TEXT NOT NULL,
    delivery_city TEXT DEFAULT '',
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc', now())
);

-- ── Row Level Security (RLS) Policies ───────────────────────────────────────
-- IMPORTANT: The app uses the anon key with server-side auth (Flask sessions),
-- so we are temporarily disabling RLS for development to prevent permission errors.

ALTER TABLE users DISABLE ROW LEVEL SECURITY;
ALTER TABLE fish DISABLE ROW LEVEL SECURITY;
ALTER TABLE orders DISABLE ROW LEVEL SECURITY;

-- ── Default Admin User ──────────────────────────────────────────────────────
-- Password: admin123 (SHA-256 hash)
INSERT INTO users (name, email, password_hash, role, city, email_verified)
VALUES (
    'Admin', 
    'admin@fish.com', 
    '240be518fabd2724ddb6f04eeb1da5967448d7e831c08c8fa822809f74c720a9', 
    'admin', 
    'Mumbai',
    true
)
ON CONFLICT (email) DO NOTHING;
